### PR TITLE
Added checkMK monitoring tool

### PR DESCRIPTION
**Pull request by ogghi**
Hi there, my first pull request. Just added CheckMK as a really nice monitoring tool.
Does that work all right with PRs like that?

### CODE REVIEW

**Comment by tborychowski** [comment]
Thanks!
But you need to also create the linked file: `apps/monitors/checkmk.md` and put some stuff into it :-)

**Comment by ogghi** [comment]
Done, just forgot this one before

**Comment by tborychowski** [comment]
Thanks very much!
I'll be testing that out today 😃

**Comment by tborychowski** [comment]
Hi,
It didn't work for me.
I had to remove the `tmpfs` param to make it work.
Do you know why?
(in the meantime I will update the page)

**Comment by ogghi** [comment]
No not sure. But do you want to commit it directly?

**Comment by tborychowski** [comment]
I did, thanks!
https://github.com/tborychowski/self-hosted-cookbook/commit/868081e873336ca6f6b90d6e4b25627a6044cb6a

**Pull request merged**
