### PR TITLE
Update README.md to include statuslist.app uptime

### PR DESCRIPTION
**Pull request by ntbosscher**

### CODE REVIEW

**Comment by tborychowski** [comment]
Hi,

Thanks for the submission.
Is there a self-hosted version of this service?

**Comment by ntbosscher** [comment]
Hi @tborychowski, unfortunately, there is not.

**Comment by tborychowski** [comment]
In that case - nice try for a self-promotion :-)

This is a repo about self-hosted apps only.

**Comment by ntbosscher** [comment]
@tborychowski fair enough. 
Just thought with uptimerobot etc that hosted/paid was fair game.

**Comment by tborychowski** [comment]
You're right. I missed these.
I will have to clean it up a bit.
Thanks for that.

**Comment by tborychowski** [comment]
Done, thanks! 
https://github.com/tborychowski/self-hosted-cookbook/commit/04d9dd418eccf4a5dbb239956dfba005274eb8de

Your app looks pretty nice, maybe in the future you could consider some sort of a "community edition", for self-hosters? ;-)

**Pull request closed without merging**
